apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook
  labels:
    app: addressbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      labels:
        app: addressbook
    spec:
      containers:
      - name: addressbook
        image: santhosh0637/fileupload:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: addressbook
spec:
  selector:
    app: addressbook
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
